'use client';

import React, { useEffect } from 'react';
import { MemberHeader } from '@/components/member-portal/MemberHeader';
import { useMemberStore } from '@/lib/store/useMemberStore';
import {
  FileText,
  Download,
  Eye,
  Calendar,
  Layers,
  FileCheck,
  ShieldCheck,
  AlertCircle,
} from 'lucide-react';

export default function DocumentsPage() {
  const { documents, fetchDocuments, isLoading } = useMemberStore();

  useEffect(() => {
    fetchDocuments();
  }, [fetchDocuments]);

  const getDocTypeBadge = (type: string) => {
    switch (type) {
      case 'booking_confirmation':
        return { label: 'Booking Confirmation', color: 'bg-blue-50 text-blue-700 border-blue-200' };
      case 'booking_agreement':
        return { label: 'Allotment Agreement', color: 'bg-purple-50 text-purple-700 border-purple-200' };
      case 'installment_schedule':
        return { label: 'Installment Schedule', color: 'bg-amber-50 text-amber-700 border-amber-200' };
      case 'payment_receipt':
        return { label: 'Payment Receipt', color: 'bg-[#EAF0E7] text-[#43612B] border-[#43612B]/20' };
      case 'applicant_photo':
        return { label: 'Applicant Photo', color: 'bg-teal-50 text-teal-700 border-teal-200' };
      case 'cnic_copy':
        return { label: 'CNIC Copy', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' };
      case 'nok_cnic_copy':
        return { label: 'NOK CNIC Copy', color: 'bg-rose-50 text-rose-700 border-rose-200' };
      default:
        return { label: 'Society File', color: 'bg-black/5 text-[#6B7462] border-black/10' };
    }
  };

  return (
    <div className="flex-1 flex flex-col min-h-screen">
      <MemberHeader
        title="Official Documents"
        subtitle="Verified allotment files, booking agreements &amp; payment receipts"
      />

      <main className="p-6 sm:p-8 max-w-7xl w-full mx-auto space-y-8">
        {/* Verification Guarantee Card */}
        <div className="bg-[#FAF9F7] rounded-2xl border border-black/[0.08] p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-start gap-3">
            <div className="w-9 h-9 rounded-xl bg-[#EAF0E7] text-[#43612B] flex items-center justify-center shrink-0 mt-0.5">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-xs font-bold text-[#151914] uppercase tracking-wider">
                Digital File Allotment Guarantee
              </h4>
              <p className="text-xs text-[#6B7462] leading-relaxed">
                All documents generated by the society management desk bear cryptographic serial identifiers and watermarked stamps under Co-operative Societies Rules 1927.
              </p>
            </div>
          </div>
        </div>

        {isLoading ? (
          <div className="bg-white rounded-2xl border border-black/[0.08] p-12 text-center space-y-3">
            <div className="w-8 h-8 border-2 border-[#43612B]/20 border-t-[#43612B] rounded-full animate-spin mx-auto" />
            <p className="text-xs text-[#6B7462]">Loading member documents...</p>
          </div>
        ) : documents.length === 0 ? (
          <div className="bg-white rounded-3xl border border-black/[0.08] p-12 text-center space-y-3">
            <div className="w-14 h-14 rounded-2xl bg-[#FAF9F5] text-[#6B7462] flex items-center justify-center mx-auto">
              <FileText className="w-7 h-7 opacity-40" />
            </div>
            <h4 className="font-display font-bold text-base text-[#151914]">
              No Documents on File
            </h4>
            <p className="text-xs text-[#6B7462]">
              You have no active booking documents registered.
            </p>
          </div>
        ) : (
          <div className="space-y-8">
            {/* Grouped by Plot */}
            {documents.map((group) => (
              <div
                key={group.plotId}
                className="bg-white rounded-3xl border border-black/[0.08] p-6 sm:p-8 space-y-5 shadow-xs"
              >
                {/* Plot Group Header */}
                <div className="flex items-center justify-between pb-4 border-b border-black/[0.06]">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-[#FAF9F5] text-[#43612B] flex items-center justify-center font-bold text-sm border border-black/[0.06]">
                      <Layers className="w-5 h-5" />
                    </div>
                    <div>
                      <h3 className="font-display font-bold text-lg text-[#151914]">
                        Plot {group.plotNumber}
                      </h3>
                      <p className="text-xs text-[#6B7462]">
                        {group.size} Allotment Dossier &bull; {group.documents.length} verified files
                      </p>
                    </div>
                  </div>
                </div>

                {/* Plot Document List or Empty State per Plot (Exception 5.7) */}
                {group.documents.length === 0 ? (
                  <div className="bg-[#FAF9F7] rounded-2xl p-6 text-center space-y-2 border border-black/[0.06]">
                    <AlertCircle className="w-5 h-5 text-[#6B7462] mx-auto opacity-50" />
                    <p className="text-xs font-semibold text-[#151914]">
                      No documents available for Plot {group.plotNumber} yet
                    </p>
                    <p className="text-[11px] text-[#6B7462]">
                      Documents are uploaded following executive committee approval and deed verification.
                    </p>
                  </div>
                ) : (
                  <div className="divide-y divide-black/[0.06]">
                    {group.documents.map((doc) => {
                      const badge = getDocTypeBadge(doc.type);
                      return (
                        <div
                          key={doc.id}
                          className="py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-black/[0.01] px-2 rounded-xl transition-colors"
                        >
                          <div className="flex items-start gap-3.5">
                            <div className="w-9 h-9 rounded-xl bg-[#FAF9F5] border border-black/[0.06] text-[#43612B] flex items-center justify-center shrink-0 mt-0.5">
                              <FileText className="w-4 h-4" />
                            </div>
                            <div className="space-y-1">
                              <div className="flex flex-wrap items-center gap-2">
                                <h4 className="font-bold text-xs sm:text-sm text-[#151914]">
                                  {doc.fileName}
                                </h4>
                                <span
                                  className={`px-2 py-0.5 rounded-md text-[10px] font-semibold border ${badge.color}`}
                                >
                                  {badge.label}
                                </span>
                              </div>
                              <p className="text-[11px] text-[#6B7462] flex items-center gap-2">
                                <span className="flex items-center gap-1">
                                  <Calendar className="w-3 h-3" />
                                  Uploaded on {doc.uploadDate}
                                </span>
                                <span>&bull;</span>
                                <span>{doc.fileSizeKb} KB PDF</span>
                              </p>
                            </div>
                          </div>

                          <div className="flex items-center gap-2 self-end sm:self-center">
                            {/* View Document (opens in new tab) */}
                            <a
                              href={doc.mockFileUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="px-3 py-1.5 rounded-xl text-xs font-semibold text-[#151914] bg-[#FAF9F5] hover:bg-black/5 border border-black/10 flex items-center gap-1.5 transition-colors"
                            >
                              <Eye className="w-3.5 h-3.5 text-[#6B7462]" />
                              <span>View</span>
                            </a>

                            {/* Download Document */}
                            <a
                              href={doc.mockFileUrl}
                              download={doc.fileName}
                              className="px-3 py-1.5 rounded-xl text-xs font-semibold text-white bg-[#43612B] hover:bg-[#365222] flex items-center gap-1.5 transition-colors shadow-xs"
                            >
                              <Download className="w-3.5 h-3.5" />
                              <span>Download</span>
                            </a>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
